### ISSUE TITLE
Promote docker-compose.yml to version 2

### ISSUE THREAD

**Issue by mkjsix** [SoftInstigate/restheart-docker#5]
Something like:

```
version: '2'
services:
   mongodb:
      image: mongo:3.2
   restheart:
      image: softinstigate/restheart
      ports:
         - "80:8080"
      depends_on:
         - mongodb
```
